# __init__.py para módulo config
from .polizas import (
    CONFIGURACION_POLIZAS,
    CONFIG_SISTEMA,
    ENCABEZADOS_CRITICOS,
    PALABRAS_CLAVE_TOTALES,
    TRANSFORMACIONES,
    MESES_ESPANOL,
)

__all__ = [
    'CONFIGURACION_POLIZAS',
    'CONFIG_SISTEMA',
    'ENCABEZADOS_CRITICOS',
    'PALABRAS_CLAVE_TOTALES',
    'TRANSFORMACIONES',
    'MESES_ESPANOL',
]
